trigger:
  - develop
  - master
  - alpha

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-greenlightbackend-docker'

steps:
  # - task: Yarn@3
  #   displayName: 'Install Packages'

  # - script: 'yarn run build'
  #   displayName: 'Build'

  # - task: Docker@2
  #   displayName: 'Build an image'
  #   inputs:
  #     repository: $(imageName)
  #     command: build
  #     Dockerfile: Dockerfile

- task: Docker@2
  displayName: 'Build and push docker image'
  inputs:
    containerRegistry: 'glp-docker-registry-connect'
    repository: 'pipelines-greenlightbackend-docker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'